QUIZ_QUESTIONS = [{'question': 'Which country has the largest hooded vulture population?',
  'options': ['Senegal', 'India', 'Egypt', 'South Africa'],
  'answer': 'Senegal',
  'badge': 'Vulture Geography Pro'},
 {'question': 'Where do hooded vultures usually nest?',
  'options': ['High cliffs', 'Large trees', 'Underground burrows', 'Open grasslands'],
  'answer': 'Large trees',
  'badge': 'Nest Master'},
 {'question': 'What is the primary threat to hooded vultures in West Africa?',
  'options': ['Habitat loss', 'Overfishing', 'Invasive species', 'Climate cooling'],
  'answer': 'Habitat loss',
  'badge': 'Conservation Hero'},
 {'question': 'Hooded vultures are known to help which of these human activities?',
  'options': ['Pollination', 'Carcass disposal', 'Water purification', 'Farming'],
  'answer': 'Carcass disposal',
  'badge': 'Eco Helper'},
 {'question': 'Which conservation status is assigned to hooded vultures by the IUCN?',
  'options': ['Least Concern', 'Endangered', 'Critically Endangered', 'Vulnerable'],
  'answer': 'Critically Endangered',
  'badge': 'Status Expert'}]
